version: '3.8'

services:
    postgres:
        container_name: postgres
        image: postgres:14.3-alpine
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: freshapp
        ports:
            - '5432:5432'
        volumes:
            - 'pg_data:/var/lib/postgresql/data/'
            
            
volumes:
  pg_data:
    driver: local
