// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/todos/[id].ts";
import * as $1 from "./routes/api/todos/index.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/AddTodoForm.tsx";
import * as $$1 from "./islands/DeleteTodo.tsx";
import * as $$2 from "./islands/SetCompleted.tsx";

const manifest = {
  routes: {
    "./routes/api/todos/[id].ts": $0,
    "./routes/api/todos/index.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/AddTodoForm.tsx": $$0,
    "./islands/DeleteTodo.tsx": $$1,
    "./islands/SetCompleted.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
